# Order in different groups: (A), (M), (M-) and (U)
all_domains = [
    "",
    "a-great-big-data-intl.fyi",
    "amklegal.co.uk",
    "anlim.de",
    "autoexpress.co.uk",
    "beleepstooked.com",
    "bestgadgetdiscounts.com",
    "besthearingaids.co.uk",
    "bestsearches.net",
    "bibinboxputhwagon.com",
    "bsmsrch.com",
    "carinsurance3m-uk.space",
    "carinsurance4d-uk.space",
    "channelweb.co.uk",
    "cio.com",
    "claimstrk.com",
    "cliniccompare.com",
    "clkmg.com",
    "clubmed.co.uk",
    "cnn.com",
    "combatsiege.com",
    "creativecdn.com",
    "csoonline.com",
    "curaprox.co.uk",
    "dailyactunews.com",
    "decanter.com",
    "desertorder.com",
    "digitalcameraworld.com",
    "doubleclick.net",
    "drivingelectric.com",
    "ecoukhomes.com",
    "etoro.com",
    "exoticca.com",
    "fertility-clinics.world",
    "flarequick.com",
    "flashtalking.com",
    "flexispot.co.uk",
    "forgeofempires.com",
    "fullnutritionsecrets.com",
    "gain-an-intl-best-online-mba-courses-usa-ace.fyi",
    "gain-intl-work-from-home.zone",
    "getsmartinsights.com",
    "globalvisitclub.com",
    "goodto.com",
    "googleadservices.com",
    "googlesyndication.com",
    "haier-europe.com",
    "hike-footwear.com",
    "homeinsulationvoucher.co.uk",
    "ilius.net",
    "infoaday.com",
    "integralads.com",
    "interactivebrokers.co.uk",
    "investinyourfamily.co.uk",
    "ivf-treatments.world",
    "kingswoodwills.co.uk",
    "lasik-eyes.co.uk",
    "latellscoaddents.com",
    "lds.xyz",
    "legacywillsquote.com",
    "linka.me",
    "llsdzktnxwnnr.com",
    "mangstomsadding.com",
    "marieclaire.co.uk",
    "mobilestairliftuk.space",
    "moneysavinghelp.co.uk",
    "mrwisebuyer.com",
    "mygenes.co.uk",
    "mysearchesnow.com",
    "navy.quest",
    "newdogdiscovery.com",
    "newskindiscovery.com",
    "nostalgicreads.com",
    "nsoftrack.com",
    "onetag.com",
    "panzer.quest",
    "perpetual-track.com",
    "pix-trk.com",
    "planetcapture.io",
    "provacan.co.uk",
    "ps.sbs",
    "pzzqvpjlfkbmb.com",
    "quelancepitylus.com",
    "reassured.co.uk",
    "responsiblelife.co.uk",
    "roinattrack.com",
    "rtbhouse.com",
    "savemoneymarket.co.uk",
    "searchlinksnow.com",
    "shefence-citional.com",
    "snzgdl.com",
    "solar-panels24-uk.com",
    "sotrends.com",
    "stairlift24-uk.space",
    "standard.co.uk",
    "strateg.is",
    "stufftopics.com",
    "suholtd.com",
    "tapashkumar.com",
    "tclfplxhhh.com",
    "thesearchgod.com",
    "theweathernetwork.com",
    "theweek.com",
    "theweeklyhub.com",
    "tips-and-tricks.co",
    "top7.today",
    "tradetracker.net",
    "travelaudience.com",
    "vodafone.co.uk",
    "volvocars.com",
    "vsgzddj.com",
    "vyager.com",
    "wallstreetviral.com",
    "whogivesacrap.org",
    "willfully.co.uk",
    "wwiqtest.com",
    "zajoltd.com",
    "zarbi.com",
    "zbrjtstrclnm.com",
]

Nothing_group = [
    "amklegal.co.uk",
    "autoexpress.co.uk",
    "besthearingaids.co.uk",
    "bestsearches.net",
    "channelweb.co.uk",
    "cio.com",
    "cliniccompare.com",
    "clubmed.co.uk",
    "cnn.com",
    "combatsiege.com",
    "csoonline.com",
    "curaprox.co.uk",
    "decanter.com",
    "desertorder.com",
    "digitalcameraworld.com",
    "drivingelectric.com",
    "ecoukhomes.com",
    "etoro.com",
    "exoticca.com",
    "flashtalking.com",
    "flexispot.co.uk",
    "forgeofempires.com",
    "fullnutritionsecrets.com",
    "getsmartinsights.com",
    "goodto.com",
    "haier-europe.com",
    "homeinsulationvoucher.co.uk",
    "interactivebrokers.co.uk",
    "investinyourfamily.co.uk",
    "kingswoodwills.co.uk",
    "lasik-eyes.co.uk",
    "legacywillsquote.com",
    "marieclaire.co.uk",
    "moneysavinghelp.co.uk",
    "mygenes.co.uk",
    "navy.quest",
    "newdogdiscovery.com",
    "newskindiscovery.com",
    "nostalgicreads.com",
    "panzer.quest",
    "planetcapture.io",
    "provacan.co.uk",
    "reassured.co.uk",
    "responsiblelife.co.uk",
    "sotrends.com",
    "standard.co.uk",
    "tapashkumar.com",
    "theweathernetwork.com",
    "theweek.com",
    "tips-and-tricks.co",
    "tradetracker.net",
    "vodafone.co.uk",
    "volvocars.com",
    "wallstreetviral.com",
    "whogivesacrap.org",
    "willfully.co.uk",
    "zarbi.com",
]

A_group = [
    "creativecdn.com",
    "googleadservices.com",
    "googlesyndication.com",
    "doubleclick.net",
    "integralads.com",
    "onetag.com",
    "rtbhouse.com",
    "travelaudience.com",
    "clkmg.com",
]

M_group = [
    "a-great-big-data-intl.fyi",  # anyrun
    "bestgadgetdiscounts.com",  # scamadviser trustscore 1
    "dailyactunews.com",  # scamdoc trustscore 1
    "hike-footwear.com",  # scamadviser trustscore 1
    "infoaday.com",  # gridinsoft trustscore 11
    "pzzqvpjlfkbmb.com",  # anyrun
    "theweeklyhub.com",  # scamdoc trustscore 1
    "llsdzktnxwnnr.com",  # anyrun
    "zbrjtstrclnm.com",  # anyrun
]

M_minus_group = [
    "bsmsrch.com",  # scamadviser trustcore 52
    "flarequick.com",  # Scam-detector trustscore 58.9
    "ilius.net",  # ipqualityscore 65 suspicious
    "mrwisebuyer.com",  # webparanoid
    "ps.sbs",  # trustpilot reviews
    "savemoneymarket.co.uk",  # trustpilot reviews
    "solar-panels24-uk.com",  # scamadviser trustscore 46
    "stufftopics.com",  # webparanoid
    "suholtd.com",  # trustpilot reviews
    "thesearchgod.com",  # scam-detector trustscore 40.5
    "vyager.com",  # scam-detector trustscore 75.8
    "wwiqtest.com",  # trustpilot reviews
    "zajoltd.com",  # trustpilot reviews
]

U_group = [
    "anlim.de",
    "beleepstooked.com",
    "bibinboxputhwagon.com",
    "carinsurance3m-uk.space",
    "carinsurance4d-uk.space",
    "claimstrk.com",
    "fertility-clinics.world",
    "gain-an-intl-best-online-mba-courses-usa-ace.fyi",
    "gain-intl-work-from-home.zone",
    "globalvisitclub.com",
    "ivf-treatments.world",
    "latellscoaddents.com",
    "lds.xyz",
    "linka.me",
    "mangstomsadding.com",
    "mobilestairliftuk.space",
    "mysearchesnow.com",
    "nsoftrack.com",
    "perpetual-track.com",
    "pix-trk.com",
    "quelancepitylus.com",
    "roinattrack.com",
    "searchlinksnow.com",
    "shefence-citional.com",
    "snzgdl.com",
    "stairlift24-uk.space",
    "strateg.is",
    "tclfplxhhh.com",
    "top7.today",
    "vsgzddj.com",
]
