from oba_analysis.data_analysis.plots.plot_categories_total_ads import (
    create_plot_for_instance_categories_data,
    create_plot_for_sessions_evolution,
)

PLOTS_DIR = "/Volumes/LaCie/OpenOBA/PLOTS/"

# Fist create the plots for the sessions evolution
# create_plot_for_sessions_evolution(PLOTS_DIR)


# OBA - ACCEPT
data = {
    "Category": [
        "Shopping",
        "Uncategorized",
        "Technology & Computing",
        "Hobbies & Interests",
        "Health & Fitness",
        "News / Weather / Information",
        "Travel",
        "Style & Fashion",
        "Business",
        "Home & Garden",
        "Education",
        "Personal Finance",
        "Automotive",
        "Arts & Entertainment",
        "Pets",
        "Real Estate",
        "Sports",
        "Food & Drink",
        "Society",
        "Non-Standard Content",
        "Careers",
        "Science",
    ],
    "NumAdsFirst6": [
        1693,
        3182,
        945,
        626,
        670,
        134,
        179,
        211,
        207,
        164,
        35,
        354,
        47,
        220,
        37,
        70,
        17,
        88,
        28,
        38,
        16,
        20,
    ],
    "NumUniqueAdsFirst6": [
        628,
        281,
        170,
        127,
        104,
        33,
        30,
        28,
        28,
        22,
        13,
        12,
        9,
        6,
        4,
        4,
        3,
        3,
        3,
        3,
        2,
        2,
    ],
}

create_plot_for_instance_categories_data(data, PLOTS_DIR, "oba_accept_ads_categories")

# OBA - DO NOTHING
data = {
    "NumAdsFirst6": [
        1858,
        278,
        640,
        318,
        154,
        94,
        280,
        278,
        140,
        126,
        200,
        90,
        140,
        6,
        30,
        12,
        20,
        20,
        10,
        10,
        10,
    ],
    "NumUniqueAdsFirst6": [
        90,
        37,
        26,
        19,
        17,
        16,
        13,
        13,
        8,
        8,
        5,
        5,
        4,
        3,
        2,
        2,
        2,
        2,
        1,
        1,
        1,
    ],
    "Category": [
        "Uncategorized",
        "Technology & Computing",
        "Health & Fitness",
        "Hobbies & Interests",
        "Shopping",
        "Business",
        "Personal Finance",
        "Home & Garden",
        "Travel",
        "Style & Fashion",
        "Real Estate",
        "Food & Drink",
        "Arts & Entertainment",
        "Science",
        "Non-Standard Content",
        "Automotive",
        "Careers",
        "Sports",
        "Society",
        "Education",
        "Family & Parenting",
    ],
}

create_plot_for_instance_categories_data(data, PLOTS_DIR, "oba_ignore_ads_categories")

# OBA - REJECT
data = {
    "NumAdsFirst6": [2350, 180, 52, 236, 41, 35, 94, 16, 322, 24, 150, 154, 18, 21, 14],
    "NumUniqueAdsFirst6": [116, 28, 26, 23, 11, 10, 10, 8, 8, 6, 5, 5, 3, 2, 1],
    "Category": [
        "Uncategorized",
        "Technology & Computing",
        "Shopping",
        "Hobbies & Interests",
        "News / Weather / Information",
        "Science",
        "Travel",
        "Business",
        "Personal Finance",
        "Arts & Entertainment",
        "Style & Fashion",
        "Health & Fitness",
        "Automotive",
        "Society",
        "Non-Standard Content",
    ],
}

create_plot_for_instance_categories_data(data, PLOTS_DIR, "oba_reject_ads_categories")


# CONTROL - ACCEPT
data = {
    "NumAdsFirst6": [
        1422,
        2215,
        823,
        330,
        542,
        448,
        363,
        112,
        37,
        262,
        160,
        140,
        164,
        101,
        98,
        6,
        20,
    ],
    "NumUniqueAdsFirst6": [
        261,
        205,
        150,
        124,
        48,
        44,
        35,
        28,
        25,
        21,
        15,
        14,
        13,
        11,
        6,
        4,
        2,
    ],
    "Category": [
        "Technology & Computing",
        "Uncategorized",
        "Hobbies & Interests",
        "Shopping",
        "Travel",
        "Health & Fitness",
        "Business",
        "News / Weather / Information",
        "Education",
        "Automotive",
        "Home & Garden",
        "Real Estate",
        "Arts & Entertainment",
        "Society",
        "Personal Finance",
        "Sports",
        "Food & Drink",
    ],
}

create_plot_for_instance_categories_data(
    data, PLOTS_DIR, "control_accept_ads_categories"
)

# CONTROL - DO NOTHING
data = {
    "NumAdsFirst6": [
        1850,
        1310,
        760,
        362,
        410,
        350,
        240,
        220,
        110,
        90,
        90,
        70,
        14,
        10,
        10,
    ],
    "NumUniqueAdsFirst6": [182, 127, 61, 53, 40, 35, 22, 21, 11, 9, 9, 7, 3, 1, 1],
    "Category": [
        "Uncategorized",
        "Technology & Computing",
        "Hobbies & Interests",
        "Business",
        "Health & Fitness",
        "Travel",
        "Arts & Entertainment",
        "Automotive",
        "Society",
        "Shopping",
        "Food & Drink",
        "Personal Finance",
        "Sports",
        "Home & Garden",
        "Science",
    ],
}

create_plot_for_instance_categories_data(
    data, PLOTS_DIR, "control_ignore_ads_categories"
)

# CONTROL - REJECT
data = {
    "NumAdsFirst6": [
        2295,
        1126,
        732,
        486,
        458,
        360,
        98,
        242,
        228,
        160,
        12,
        14,
        40,
        20,
        14,
        4,
    ],
    "NumUniqueAdsFirst6": [185, 84, 52, 45, 42, 36, 24, 23, 19, 14, 6, 5, 4, 2, 1, 1],
    "Category": [
        "Uncategorized",
        "Technology & Computing",
        "Hobbies & Interests",
        "Health & Fitness",
        "Travel",
        "Business",
        "News / Weather / Information",
        "Automotive",
        "Arts & Entertainment",
        "Personal Finance",
        "Sports",
        "Home & Garden",
        "Food & Drink",
        "Shopping",
        "Society",
        "Science",
    ],
}

create_plot_for_instance_categories_data(
    data, PLOTS_DIR, "control_reject_ads_categories"
)
